### ISSUE TITLE
Enable App Modernization use case with Toolkit

### ISSUE THREAD

**Issue by seansund** [ibm-garage-cloud/planning#190]

**Comment by csantanapr** [comment]
Link to https://github.com/ibm-garage-cloud/garage-pipelines/pull/1

**Comment by csantanapr** [comment]
Some notes on latest meetting with AppMod team:

- [ ] Enable pipelines (jenkins, tekton) for liberty apps
- [ ] Add code pattern app for liberty (app was modernize from WAS to containers) deploy with pipelines
- [ ] Add terraform for iteration zero to deploy tools for metrics (prometheus, graphana) for liberty
