### ISSUE TITLE
Pipeline refresh

### ISSUE THREAD

**Issue by seansund** [ibm-garage-cloud/planning#277]
## Fixes

- [x] IKS role permissions to deploy into pipeline namespace - #279
- [x] IKS "credentials not found" error (doesn't cause an issue for public repo but will for private) - #280 
- [x] Rebase Inventory Svc on latest Starter Kit and incorporate new Pact testing logic #245 
- [x] Rebase Inventory BFF on latest Starter Kit and incorporate new Pact testing logic #282
- [x] Rebase Inventory UI on latest Starter Kit #281
- [x] Fix jenkinsUrl issue
- [x] Implement version numbering in tekton-tasks
- [x] Automate version numbering in tekton-tasks
- [x] Implement version numbering in garage-pipelines #212 
- [x] Fresh install on IKS, pipeline register template-node-typescript does not start, failing to load pod 
- [x] The CLI should give a clear error message if `igc pipeline` is called without calling `igc sync --dev`

## Documentation

- [x] Update CLI documentation in Dev Guide
- [x] Update Deploy App documentation in Dev Guide
- [ ] Update Inventory App documentation in Dev Guide

### CLI

- [x] Push CLI beta changes to master
- [x] Publish release with release notes

### Starter Kits

- [x] Push template-node-typescript `dev` changes to master and tag release
- [x] Push template-graphql-typescript `dev` changes to master and tag release
- [x] Push template-node-react `dev` changes to master and tag release
- [x] Push template-java-spring `dev` changes to master and tag release
- [x] Delete old starter kits from `ibm-garage-cloud` org

### Code Patterns

- [x] Push Inventory UI Code Pattern dev changes to master and tag release
- [x] Push Inventory BFF Code Pattern dev changes to master and tag release
- [x] Push Inventory Svc Code Pattern dev changes to master and tag release

### Pipelines

- [x] Push garage-pipeline changes in `dev` branch to master (the changes that have already been applied to the Starter Kits
- [x] Push tekton-task dev changes to master
- [x] Update Tekton Resource terraform module to install from release yaml
- [x] Update Iteration Zero to use latest Tekton Resource
