### ISSUE TITLE
Prepare for Cloud Native Toolkit workshop

### ISSUE THREAD

**Issue by seansund** [ibm-garage-cloud/planning#917]
- [x] Update Artifactory version - Ramya
- [x] Update SonarQube version - Ramya
- [ ] Update SonarQube storage and password management
- [x] Developer Dashboard cleanup
- [x] Update base images in starter kits to pass image validation
- [x] Replace React UI starter kit with modern version - Noe
- [x] Rebase Inventory UI sample app on new react starter - Noe
- [x] Rewrite instructions for Inventory UI creation - Noe
- [x] Refresh Inventory BFF and Inventory Service sample apps

**Comment by RamyaRaghuveera** [comment]
Dev dashboard changes mentioned by Matt: https://gsicsi.slack.com/archives/C03FRBNHL6S/p1652981827145659
